### ISSUE TITLE
[Enhancement] Gen 6 Support

### ISSUE THREAD

**Issue by Xanadu16** [Dabomstew/universal-pokemon-randomizer#1]
Hold on a minute: hear me out.

With the recent advancements in 3DS hacking, we've managed to decrypt the ROMs for X/Y and OR/AS. I don't suppose its too unreasonable to start thinking about randomizing their specific decrypted contents related to the pokemon data tables and wild grass data and such then allow us to repackage the ROMs?

http://projectpokemon.org/wiki/Pokemon_X/Y_3DS_Structure
http://projectpokemon.org/wiki/Pok%C3%A9mon_XY_Save_File_Structure

There's not a 3DS structure for ORAS yet, but
http://projectpokemon.org/wiki/Pok%C3%A9mon_ORAS_Save_File_Structure

**Comment by Dabomstew** [comment]
This isn't out of the question, but I don't currently have the resources to test anything I make for this. Check back in a month or two and maybe...

**Comment by Xanadu16** [comment]
Just as a note, you might have to split randomization into "two" modes for Light and Heavy because there would almost definitely be Wi-Fi incompatabilities.

**Comment by Dabomstew** [comment]
Locking for now as pk3DS already fulfills this function as well as is required for the time being.
