### ISSUE TITLE
Unplayable randomized Moemon ROM

### ISSUE THREAD

**Issue by Undrhil** [Dabomstew/universal-pokemon-randomizer#10]
I have compiled the latest source code of the Randomizer.  If I apply the randomizer to a Emerald or Fire Red game ROM which has had the Moemon patch applied to it, the game will not load.  It does not get to the Gamefreak logo.

As far as I am aware, the patch I am using for Moemon only changes Pokémon sprites.  Any idea what could cause it?

**Comment by Dabomstew** [comment]
There were some issues with detecting Fire Red rom hacks that didn't expand the Pokedex.  I resolved these in 83e21d9, so try Moemon Fire Red again. Emerald ROM hacks are not officially supported as of right now, though I will take a look soon and see why that particular hack breaks.

**Comment by Dabomstew** [comment]
Tried out Moemon Emerald and I could not reproduce any kind of bootup failure. The game ("Moemon Project Revival Emerald 1.1.0") randomized just fine for me. Make sure your emulator is setup to play the GBA games correctly (Flash 128K save setting).

**Comment by Undrhil** [comment]
I am not referring to the ROM Hack of Moemon, I'm referring to the IPS patch which only replaces the Pokémon sprites with the Moemon sprites in the Emerald ROM (and there is another one of those setup which does the same for the Fire Red ROM.)  I am able to play randomized Pokémon Emerald just fine if I have not applied the Moemon IPS patch to it.

**Comment by Dabomstew** [comment]
I wasn't aware there was a difference - the IPS patch I named does only change sprites, to my knowledge.

**Comment by Undrhil** [comment]
I've seen let's plays of a Moemon ROM Hack that also adds more water places and changes up the layout of some of the routes (adding fences to Route 101, for instance.)

**Comment by Dabomstew** [comment]
Hm, okay. In any case, can you name the specific Moemon patch you're using and/or link to where it's distributed (the IPS, not the ROM, obviously) so I can check it if it isn't the same one that I named?

**Comment by Undrhil** [comment]
Actually, I think the one I just found is newer than the one I have.  Let me try it and I'll let you know what it does.

**Comment by Undrhil** [comment]
OK, when I apply any of the Moemon patches that I have, the game plays fine before being randomized.  However, after being randomized, the sprites are all garbled and the game locks up during choosing your starter Pokémon.  I can send you the Patches I have, but the latest one I found with a google search for Pokémon Emerald Moemon IPS.

**Comment by Dabomstew** [comment]
Alright, I'm still not having any issues, so I'll have to ask you to do the following to see if this is just down to the games/patches you're using or it's some kind of bug that only happens on certain PCs:

* Get a clean copy of Emerald (U)
* Make sure it boots and you can select a starter without crashing (should be no problem)
* Get Moemon Revival Emerald 1.1.0 from https://forums.pokemmo.eu/index.php?/topic/44698-ipsmoemon-project-revival-rse-10514-update/
* Patch it to the Emerald ROM
* Again, make sure it boots and you can pick a starter no problem
* Randomize the patched ROM with whatever settings you want, but note down what you picked somewhere (or make a file with "Save Settings")
* Check to see if the sprite garbling thing still happens.

This exact process produces a perfectly working Moemon Emerald randomized game for me, so if it doesn't for you then something is extremely fishy. Hopefully it does work - if it doesn't, it should at least allow me to get closer to solving the problem.

**Comment by Undrhil** [comment]
I actually refreshed my copy of the source code from GitHub, rebuilt it, got a new copy of the ROM and applied the Moemon patch.  Then I ran the newly compiled randomizer and applied my settings and everything is working.  I guess there was a bug in the code that I got yesterday which caused it?  Anyway, it's working now.  Thanks for helping me out with this :)
