### ISSUE TITLE
Migrate to HTTPS.

### ISSUE THREAD

**Issue by Asday** [Dabomstew/universal-pokemon-randomizer#108]
As you are providing a downloadable executable on your website, serving over HTTP is highly irresponsible - it is trivial to perform a "man in the middle" attack and swap out the executable for a malicious one.

Please migrate to HTTPS.  This is now both free and easy to do thanks to [LetsEncrypt](https://letsencrypt.org/getting-started/).

**Comment by Dabomstew** [comment]
Fundamentally I agree, and the website should get HTTPS enabled when I get a chance sometime over the next few days. Not sure about updating the randomizer itself to reference HTTPS links though, updates have been stopped entirely for quite a while.

**Comment by Asday** [comment]
I don't have any experience with Java, so I can't hazard a guess, sorry.

That said, I instantly disabled auto-update, so...

**Comment by Dabomstew** [comment]
The main website is now forced HTTPS. An exception has been made for the autoupdate folder for now to prevent any issues with that. As was sort of implied by your post, any users concerned with security should disable that function. It is very unlikely that any new updates come out regardless.

**Comment by Asday** [comment]
Fantastic, thank you very much.
