### ISSUE TITLE
Another feature request (is there a better place for this?)

### ISSUE THREAD

**Issue by Undrhil** [Dabomstew/universal-pokemon-randomizer#11]
Is there a way for you to add in the ability to randomize evolutions?  I understand that this would probably have to be exclusive of the other evolution tweaks, but I think it would be neat if I have no idea what my Pokémon will evolve into or when, if possible.

**Comment by Dabomstew** [comment]
Randomized evolutions have been added as of https://github.com/Dabomstew/universal-pokemon-randomizer/commit/85c0f797a51038e6d4b81f38315b9c5f0e63f5e7 . Credit to pk3DS (the gen6 randomizer/editor) for giving me some idea of how to put together sane randomization.
