### ISSUE TITLE
Black/White 1 trainer hard crashes

### ISSUE THREAD

**Issue by cleartonic** [Dabomstew/universal-pokemon-randomizer#129]
There appears to be a bug in Black/White 1 with fast text. When the player encounters a trainer and mashes  the confirm button too quickly, there's a chance the game locks up completely. 

It's notable that this bug is not at all present in Black/White 2. Without knowing fully about how fast text was designed, it seems like the fast text was designed initially for B/W2 as the fast trainer starting dialogue handles the trainers' starting animations in B/W2 well- but perhaps causes something buggy in B/W1 where there are no animations. 

Can this please be addressed? A few of us want to regularly race both B/W1 and B/W2, and this hardlock causes major problems for us. Thank you

**Comment by Ajarmar** [comment]
I would also like to see this addressed. Thank you.

**Comment by Yuranah** [comment]
I can't stop myself from mashing from time to time so this kept happening. I also would like this to be addressed. Thank you very much

**Comment by Dabomstew** [comment]
If this is actually a thing I would recommend just not using the option for Black/White 1, as slow as it may feel. I don't actually have knowledge of the programming required to create the Instant Text codes for gen4/5, they are just ported Action Replay codes as acknowledged in the program changelog - so a fix is unlikely to be forthcoming.

**Comment by cleartonic** [comment]
That's a shame - a randomizer designed for playability and races having a major breaking bug seems like something that should be fixed. Fast text is realistically what makes racing the game viable for us. 

Some of us can potentially work on programming a fix for the Gen 5 .ips files in universal-pokemon-randomizer/src/com/dabomstew/pkrandom/patches/. If possible, any leads on the origin of these codes would be helpful. Can you please point us in the direction of how these were implemented or where they came from, at least?

**Comment by Dabomstew** [comment]
The code changes provided by the randomizer have always been experimental to some degree, and the randomizer stopped having any kind of major update 2 years ago. That said, I can still try to provide the info you're looking for.

To expand upon what I said in my previous comment, the Gen 5 Instant Text patches were sourced from Action Replay codes which edited the ARM9 code in-memory. This code change can also just be done on the code binary itself, so that is exactly what the IPS patches do - no more, no less. I don't seem to have any more specific research notes to provide on the spot, but the Action Replay codes themselves are easily found through a quick search as is the AR code format that I would have used to translate them into binary changes.

**Comment by Dabomstew** [comment]
And some quick links to what I alluded to earlier:

AR code format - http://nintendq.forumotion.com/t45-action-replay-code-types

BW1 code (one particular source of it, I couldn't find the original source back in 2016) - https://www.supercheats.com/nintendods/pokemon-black/6304/ar-codes/many-different-codes/
BW2 code (same again) - https://gbatemp.net/threads/us-pokemon-black-2-white-2-action-replay-codes.335734/page-10

**Comment by cleartonic** [comment]
Alright. Thank you for looking. If we develop a fix we'll report back

**Comment by cleartonic** [comment]
Ajarmar and I spent a fair amount of time, and were able to fix this problem - the solution was to add in some start-of-battle checks to disallow inputs during the sensitive time frame that resulted in crashes. Also, we added an option to disallow Professor Juniper in both BW1 and BW2 from giving the player the Lucky Egg. 

Pushed to:
https://github.com/Ajarmar/universal-pokemon-randomizer/

**Comment by Ajarmar** [comment]
We're doing a race this weekend, so I'll make a pull request after that just so we can make sure that everything works first.
