### ISSUE TITLE
The randomizer is not using the correct form of randomization

### ISSUE THREAD

**Issue by Hubbi** [Dabomstew/universal-pokemon-randomizer#13]
I tested this on Emerald and Diamond.
When i choose 'Random' under the 'Wild' tab, i expect that each encounter will be picked from the pool of ALL pokemon in that region, right? So each encounter should essentially be 100% random.

This is not the case, as each encounter will go through the same 5-6 random pokemon pool, as if i had chosen 1-1 mapping.

**Comment by Dabomstew** [comment]
This could probably use better documentation/explanation, but it isn't a bug. 

Basically, the randomizer doesn't change how encounters work in the game in any way. Encounters in Pokemon games work in a way where each area has a certain number of encounter slots. Without modifying the game mechanics it isn't possible to make a certain area have more than that number of unique encounters appear.

If you want "truly random" encounters like you describe out of the entire Pokemon pool, use a cheat code (GameShark/Action Replay) instead.

**Comment by Hubbi** [comment]
Then what's the difference between 'Random' and 'Area 1-1 mapping'?

**Comment by Dabomstew** [comment]
In the real Pokemon games, especially earlier gen games, all of an area's encounters would be filled by a very small number of unique Pokemon. An example is Route 1 in Gen1 & FR/LG, where all 10(12 in the remakes) encounter slots are filled by Pidgey/Rattata. Area 1-1 will use this same mapping and only put 2 unique encounters on the route, while Random will at least fill every possible slot.
