### ISSUE TITLE
Tooltips should last longer

### ISSUE THREAD

**Issue by Parker8283** [Dabomstew/universal-pokemon-randomizer#15]
The tooltips that are provided on almost all of the options should last longer. Especially the longer ones, it gets annoying to have to move the mouse off and back on again to read them because the tooltip keeps disappearing. I feel that the tooltip shouldn't have a timeout, as when we are done with it, we would just move our mouse, which should be the signal to stop drawing the tooltip.

**Comment by Dabomstew** [comment]
I completely agree, tooltip duration was just something I hadn't thought about before / didn't know how to do. Will be updated for next release.

**Comment by Dabomstew** [comment]
Infinite tooltip timeout has been implemented in v1.7.0b as of commit https://github.com/Dabomstew/universal-pokemon-randomizer/commit/46a3776736896c26aafa64f497d42a0ecded366e .
