### ISSUE TITLE
Some tabs' contents extend beyond accessible area

### ISSUE THREAD

**Issue by wlgerste** [Dabomstew/universal-pokemon-randomizer#16]
For some tabs, (such as Pokemon Traits and Misc Tweaks) the text or options themselves are beyond the window/frame that is visible, and (to my knowledge) I cannot scroll down/to the size nor can I change the window/frame size to make these options visible and selectable. Effectively, some options are unable to be selected at this time due to being out of view.

This issue occurs for multiple versions of Java (all versions I have installed encounter it. Java SE Runtime 1.8.0_72-b15 is my default. Can provide further info if needed). 
I am running Linux Mint 17 (64-bit) with Cinnamon desktop (v2.2.16). 
I have not tested this on any other distros or operating systems, so I cannot say that this isn't a distro specific issue. 

If there is any further info needed, please let me know. Will check back here at least daily to monitor if further info is requested.

**Comment by Dabomstew** [comment]
Yes, all the spacings are pretty tight and only really designed for Windows native appearance as of version 1.7.0. Going to look into adding more space / allowing resizing again in the next release. For the time being, any kind of screenshot of just how badly things are cut off visually could help me decide on the actions I take.

**Comment by EvilSpork** [comment]
I'm seeing this issue on Windows 10 with Java SE Runtime 8.0.730.2. I have tried different DPI scaling but not a different Java version. See attached screenshot for details of what is cut off.

![traits](https://cloud.githubusercontent.com/assets/4196603/13486071/a010ea8e-e0c2-11e5-9687-43644efe0d11.png)
![starters](https://cloud.githubusercontent.com/assets/4196603/13486074/a2fb68c8-e0c2-11e5-9d47-7dc8d9cff02b.png)

**Comment by Dabomstew** [comment]
The tabs going into two tiers because of the increased font size is what is making it as bad as it appears in that screenshot. I have received screenshots of how it looks on Linux/Mac where the tabs get a scroller arrow instead and there is a cutoff at the bottom still but it is much smaller. In any case I need to rethink the UI to stop it depending on default Windows DPI/zoom settings/fonts which was obviously a very bad design decision to begin with. Still pondering as to how I'll approach it though.

**Comment by EvilSpork** [comment]
I changed my DPI scaling to 100% and it looked the same as the screenshot at 150%. I thought for sure that was my issue. I'll test some more and report back if I find anything.

**Comment by Dabomstew** [comment]
Actually, looking further at the screenshot I can see what's going on to some degree. In your screenshot all the bolded/styled text is the correct size while everything else is too big. That implies that all text which I didn't give a specific style to is using some kind of system default for font face/size and the UI itself could possibly be fixed if this were not the case. This is consistent with the Mac screenshot I received too.

**Comment by Dabomstew** [comment]
"Fixed" by numerous GUI changes implemented in v1.7.0b as of commit https://github.com/Dabomstew/universal-pokemon-randomizer/commit/46a3776736896c26aafa64f497d42a0ecded366e .
