### ISSUE TITLE
Would you be willing to accept a new feature to disable exotic berries and mail items in fr/lg?

### ISSUE THREAD

**Issue by andrew-wilcox** [Dabomstew/universal-pokemon-randomizer#17]
I'd like to implement that, but I noticed you only accept pull requests "if they're universal." Would you accept this feature if it was only done for gen 3? I'm not really interested in working on every generation.

**Comment by Dabomstew** [comment]
Disable as in what exactly? "Ban bad items" already removes the likes of mail and berries from the randomized item possibilities so I'm not sure what the extra point of this is. Also, that text probably needs updating. Things like what you're suggesting could probably be done as a minor setting/misc tweak, which are allowed to only support one game or a small set of games. The text as it stands is mainly referring to adding more major features. (like if I got a pull request for Randomized Mart Inventories, or something on that kind of scale, but it only supported one generation)

**Comment by andrew-wilcox** [comment]
Ah, my apologies, I was under the impression "ban bad items" was a control for overpowered things early, not to eliminate useless pickups. This satisfies my request fine, thanks for taking the time to respond.

**Comment by Dabomstew** [comment]
No worries. In any case, thanks for pointing out that text to me. Giving the impression that everything in the randomizer had to be universal wasn't my intention by any means - there is plenty of stuff that only applies to certain games, especially under the tweaks section. It has been updated now.
