### ISSUE TITLE
"Every Pokemon starts with 4 moves?" Option not working on Silver Version.

### ISSUE THREAD

**Issue by RedNitro7** [Dabomstew/universal-pokemon-randomizer#19]
Basically what the title says. The option doesn't appear for Silver Version. It does work with Crystal version though. I haven't tested with Gold Version yet. It does work with Gen I games (Red at least) and it worked on earlier versions of the UPR so I'm pretty sure this is a bug.

**Comment by Dabomstew** [comment]
Not a bug. This feature is not supported in Pokemon Gold/Silver for technical reasons (the ROM bank where the movesets are kept doesn't have enough free space for all the extra entries required). As you've mentioned yourself, pretty much every other game allows this feature.
