### ISSUE TITLE
Gen 3 move names garbled in log file

### ISSUE THREAD

**Issue by jpmac26** [Dabomstew/universal-pokemon-randomizer#2]
I have tested this with roms for Emerald and FireRed. When I choose to save a log file after choosing to update moves, the move names are glitchy symbols instead of the proper move names. However, all other generation games seem to save the move names in the log file correctly.
![glitchy log file](https://cloud.githubusercontent.com/assets/2925767/8096325/dbf18d7e-0f8a-11e5-8362-55b78d1131fb.png)

**Comment by Dabomstew** [comment]
Yeah, emerald/FRLG were trying to read move names from the move data pointer instead of the move names list as of 1.63. Fixed.
