### ISSUE TITLE
Gen3 Starter mixup?

### ISSUE THREAD

**Issue by SibirianPns** [Dabomstew/universal-pokemon-randomizer#31]
When randomizing the Starters in Leafgreen there seems to be a little mix-up: When comparing the contents in the log file with the actual rom Starter 1 is the most left one, so Starter 2 should be the middle one and Starter 3 the most right one but in reality Starter 2 is right and Starter 3 is the middle one. Isn't that a bit counter intuative? Pretty minor issue but still...

"Squirtle" is the middle starter:
![bug_randomizer](https://cloud.githubusercontent.com/assets/21988345/18232484/be599518-72d0-11e6-91a2-0d3b74dc027c.png)

**Comment by Dabomstew** [comment]
The order of the starters in the log is set based on the type triangle to make the rival starter code work easier. So it won't always match the order on the table/in the bag for later gens of Pokemon.
