### ISSUE TITLE
HG/SS Move Category

### ISSUE THREAD

**Issue by kittikatt** [Dabomstew/universal-pokemon-randomizer#32]
I've tried multiple times changing the move category using the randomizer, but every time I do, it just keeps them as they are in the vanilla games. The log file says changes have been made, but checking in game shows they haven't actually been applied. Move category worked just fine on B2 yesterday, so it might just be on Soul Silver.

**Comment by Dabomstew** [comment]
Fixed in commit 49e1d38, there just hasn't been a randomizer release since then. For the record this only affected Gen 4.
