### ISSUE TITLE
Getting baby pokemon as starter

### ISSUE THREAD

**Issue by mithlug** [Dabomstew/universal-pokemon-randomizer#36]
Hi!
Love the stuff, sry to report an issue. In changelog for 1.7.0 you say baby pokemons won't be chosen as starters:
"The option to select a random starter with 2 evolutions will now include Pokemon with no prevolutions and at least 2 stages of evolution."
I got a Cleffa on my Gen 4 game after choosing Random (basic pokemon with 2 evolutions)

EDIT: I'm probably reading that wrong, I just realized. But please confirm that I read it wrong.

**Comment by Dabomstew** [comment]
Yeah, you read it wrong (sorry for the late reply). The wording might be a bit confusing as I'm not sure "prevolution" is actually a word. Might adjust it at some point.
