### ISSUE TITLE
[Feature Request] Expanded Doubles in Gen 3 onward?

### ISSUE THREAD

**Issue by raekuul** [Dabomstew/universal-pokemon-randomizer#39]
Can and would you add an option to expand Double battles, for example to all trainers with four or more Pokemon?

**Comment by Dabomstew** [comment]
In theory this is possible, but in practice it's dodgy for a few implementation reasons - for example in Gen 3 there is a nasty bug if you start a double fight with only one Pokemon alive, and any single fight just straight out changed to double would put you in danger of doing this. ROM hacks in general are where you should look if you want an experience with more double battles.
