### ISSUE TITLE
Randomizer not randomizing in-game trades

### ISSUE THREAD

**Issue by JkHowling** [Dabomstew/universal-pokemon-randomizer#45]
I've had this problem for awhile now, unfortunately. Everything else on the randomizer seems to work perfectly fine- except, no matter the rom, no matter the game.. I'll select "randomize in-game trades" and it NEVER goes through. It puts down what the randomized ones SHOULD be, on the randomization log, but for whatever reason.. the in-game trade still asks for and offers the same mon it always did. I don't know if its a text bug or what, but using different roms and re-downloading the randomizer has worked in solving this.

**Comment by Dabomstew** [comment]
This likely is just text not being updated in some games. It has to be done manually in some generations and I'm not sure if I ever bothered with checking in game trade text in later generations.

**Comment by JkHowling** [comment]
Alright, I'll just use the randomization log to check what the actual trades are I suppose. The odd thing is, I can swear it used to work fine before- then, suddenly, it didn't. Not sure what happened. Thanks for the response.
