### ISSUE TITLE
Error when trying to randomize Red rom

### ISSUE THREAD

**Issue by JkHowling** [Dabomstew/universal-pokemon-randomizer#47]
I keep getting an error when trying to randomize a Red rom. The message it gives me is simply 

"There was an unhandled exception trying to save your ROM to disk"

This is the note file it gives me. I don't understand it so..

[error_2017-03-31-21-50-03.txt](https://github.com/Dabomstew/universal-pokemon-randomizer/files/887373/error_2017-03-31-21-50-03.txt)

**Comment by ChatmyBee99** [comment]
This could possibly be caused by the ROM not being clean, or it being a bad dump (but good enough so the program reads it). Maybe try downloading a ROM from a different source.
