### ISSUE TITLE
Missing Items in tabbed layout

### ISSUE THREAD

**Issue by mdewey** [Dabomstew/universal-pokemon-randomizer#49]
I noticed that some randomizing options are missing in the tabbed layout. Specifically the "Change Impossible Evos"  

I am not sure what else is missing but it feels like it is missing more than just that in the Tabbed view vs the scrolling view

**Comment by Dabomstew** [comment]
This program (and other Java Swing programs) has issues with high-DPI displays on Windows which use scaling. This won't be addressed until Java 9 is released.
