### ISSUE TITLE
Cannot use the "Update Type Effectiveness" option

### ISSUE THREAD

**Issue by jdeitsch** [Dabomstew/universal-pokemon-randomizer#5]
I've tried on several different ROMs and have thus far failed to get anything other than grayed-out taunting from the checkbox.  This seems to be the magic bullet that could fix the errors in several different type-effectiveness match-ups, like Ghost - Psychic, Dragon - Dragon, and Water - Electric.

**Comment by Dabomstew** [comment]
This option is only meant to work in Gen 1, where a few type matchups are notably different from Gen2 to Gen5 (Ice->Fire, Ghost->Psychic, Poison->Bug). What exactly was your intention in using it?

**Comment by jdeitsch** [comment]
In Gen 5 (Black 2 specifically) randomization results in some incorrect type matches, i.e. Ghost is normally effective against Psychic and vice versa, while dragon is normally effective against dragon rather than being doubly effective.
