### ISSUE TITLE
jumbled sprites (the overworld sprites) 

### ISSUE THREAD

**Issue by Tigerman277** [Dabomstew/universal-pokemon-randomizer#51]
i beat a battle in sprout tower and then when i went back to the overworld it was weird everyone was black squares, even my kabuto wasn't safe! ( my rating for this randomizer time! ) 0/10

**Comment by CharmyBee99** [comment]
I never had any issue like this happen to me, what emulator are you using?
I personally reccomend using BGB or Gambatte for Gameboy and Gameboy Color games...
Obviously, emulation error.

**Comment by Dabomstew** [comment]
This sounds much more like HeartGold/SoulSilver which do not play nice with current emulators at all. Almost certainly not randomizer related.
