### ISSUE TITLE
How do I change the language from japanese/chinese?

### ISSUE THREAD

**Issue by CMGaming** [Dabomstew/universal-pokemon-randomizer#55]
I want English, and I'm sorry I don't know but its set to Japanese/Chinese! Please tell me how to fix this soon!
Thanks in advance,
CMGaming

**Comment by CharmyBee99** [comment]
You mean the randomizer?

**Comment by Dabomstew** [comment]
The randomizer has no non-English text to speak of, which is admittedly a missing feature but probably not one that will ever be resolved. If you somehow got a Randomizer that doesn't use English, it's either not an official release or a problem with your system.
