### ISSUE TITLE
catch them all mode

### ISSUE THREAD

**Issue by naruhina2016** [Dabomstew/universal-pokemon-randomizer#58]
Hi,

I was wondering what does catch them all mode do.
and how does it work?.

cheers

**Comment by RCTMASTA** [comment]
I don't actually know the code specifics but I think it's safe to assume that it removes a Pokemon from the possible randomizations that an encounter slot can be every time it randomizes a slot to that Pokemon, until it goes through everything in the Pokedex and resets the "used" list.

eg. slot 1 on kanto route 1 is randomized to a Mewtwo on Red; Mewtwo will now not appear in another encounter slot until another 150 encounter slots have been randomized.

This essentially has the effect of ensuring that every Pokemon in that respective game's Pokedex is catchable _somewhere_.

**Comment by naruhina2016** [comment]
but still how do i know which pokemon will appear then?

**Comment by Dabomstew** [comment]
As RCTMASTA said, every Pokemon will be *somewhere*. Once you find it once (on a trainer, or in the wild) you can use the ingame Pokedex AREA option to see where it can be found. Until you find it once, you will have to look mostly blind or check the log file if you're that way inclined.

**Comment by naruhina2016** [comment]
i see thanks for the explanation i really appreciate it
