### ISSUE TITLE
2 issues in 1

### ISSUE THREAD

**Issue by deen94** [Dabomstew/universal-pokemon-randomizer#64]
1. Dusk and dawn stone weren't available in fr/lg so I don't know how to get Gallade (I'd recommend changing both to moon stone)
2. If you scroll too fast on the randomizer screen then the letters get choppy and weird, I attached a photo as an example
![screen shot 2017-06-22 at 9 20 12 pm](https://user-images.githubusercontent.com/29646367/27464026-9cc937be-5790-11e7-917d-e4e783226117.png)

**Comment by CharmyBee99** [comment]
First off... Both the Dusk and Dawn stones are Generation 4 items, while Gallade was introduced in Gen 4 as well, while FR/LG is still, generation 3, in Generation 4 though, you can try and get them via the Underground, or pick them up from somewhere...

**Comment by deen94** [comment]
@CharmyBee99 Yes, but if you updated the pokemon then Gallade is available so change impossible evos should make it possible to get one.

**Comment by Dabomstew** [comment]
There is no option in the randomizer that adds Gallade to Gen 3 games and ROM hacks aren't officially supported. I'm afraid you're on your own for issue 1.

As for issue 2, that is very odd indeed but not something I can easily reproduce or fix. It might well be a Java bug rather than anything to do with my code anyway.

**Comment by CharmyBee99** [comment]
Even though some romhacks are supported, again, officially, they aren't supposed, most simple romhacks that like modify the sprites, or text should work, but there's always a possibility that they won't. While the support is getting better (for example, Pokémon Liquid Crystal loads, but the randomizer cannot randomize it yet), @Dabomstew still cannot ensure that a certain romhack will work. Your only option is to modify Kirlia's evolution data yourself with other tools.
