### ISSUE TITLE
Randomizer wont make the randomized rom

### ISSUE THREAD

**Issue by xloliwinx** [Dabomstew/universal-pokemon-randomizer#68]
java.lang.NullPointerException
	at com.dabomstew.pkrandom.Randomizer.maybeChangeAndLogStaticPokemon(Randomizer.java:738)
	at com.dabomstew.pkrandom.Randomizer.randomize(Randomizer.java:343)
	at com.dabomstew.pkrandom.gui.RandomizerGUI$3.run(RandomizerGUI.java:1528)
That is the error code that i get every time i try to randomize a pokemon rom

**Comment by CharmyBee99** [comment]
I think you're using a rom hack, for now, only clean games are supported, however some small hacks may be supported as well, first, tell us what you're trying to randomize.

**Comment by xloliwinx** [comment]
I'm trying to randomize a rom hack that is called Pokemon Volt white 2 and I've seen youtubers randomize this game with the universal randomizer so that's why i'm so confused

**Comment by CharmyBee99** [comment]
first, try randomizing a clean rom, to see if it's the problem with the hack itself. There's no official support for any romhacks yet, so it's normal that they may not work...

**Comment by xloliwinx** [comment]
Alright i'll try that thank you for the advice :)
