### ISSUE TITLE
Pokémon don't gain any EXP

### ISSUE THREAD

**Issue by Maronbeere** [Dabomstew/universal-pokemon-randomizer#72]
I made a randomized the German version of Pokémon Black 2 and used this config:
Random Seed: 255836295302187
Config String: ¬XAgQUKgjuAfEB9AECAJyoigACMgAAKsYeAggqAAAAAAAAAgAyE1Bva2Vtb24gQmxhY2sgMiAoRykRUEor48M4ig==
For some reason, my Pokémon won't get any EXP whatsoever.
I hope someone can help, thanks in advance!

**Comment by CharmyBee99** [comment]
this is not the randonizer's issue, most likely your emulator isn't good enough and failed the anti-piracy test, triggering the anti-piracy mechanisms, my recommendation is to try a different emulator first.
