### ISSUE TITLE
Diamond and Pearl versions are never 100% random.

### ISSUE THREAD

**Issue by Hubbi** [Dabomstew/universal-pokemon-randomizer#8]
This is a bug i encountered a while ago.

When i global 1-1 randomize the diamond and pearl roms, they are never fully randomized. On the early rutes, bidoofs will always appear, and the first cave always has geodudes in them.

other 'normal' pokemon can be seen on the different routes as well, though a majority of pokemon are successfully randomized, there will always be a few that aren't.

**Comment by Dabomstew** [comment]
Looking at some earlier research it appears I actually knew about this but was unable to find a complete solution at the time. Leaving this reply to make it known that I am aware of this and will attempt to fix it, but no guarantees.

**Comment by Dabomstew** [comment]
Solved as of 830321a , release soon.
